// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6rRCW8KuHXlWHo8nvtz1oHbuwuWigZoo',
    appId: '1:228865824711:web:43120b0e5ecbdae1006be2',
    messagingSenderId: '228865824711',
    projectId: 'sukaemam-final-test',
    authDomain: 'sukaemam-final-test.firebaseapp.com',
    storageBucket: 'sukaemam-final-test.firebasestorage.app',
    measurementId: 'G-VS3XLV1G7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQcdfLQ0RFydUYwMvFMqCJFDalHeeS7hE',
    appId: '1:228865824711:android:6282e8ccdc4062b8006be2',
    messagingSenderId: '228865824711',
    projectId: 'sukaemam-final-test',
    storageBucket: 'sukaemam-final-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXHX3b3P1_BIrFwiZyTLN4H8QN5LFvrg0',
    appId: '1:228865824711:ios:06ecd83f09106042006be2',
    messagingSenderId: '228865824711',
    projectId: 'sukaemam-final-test',
    storageBucket: 'sukaemam-final-test.firebasestorage.app',
    iosClientId: '228865824711-vg0cmm4kad0igibnlmcf0md0p4bqamd9.apps.googleusercontent.com',
    iosBundleId: 'com.example.sukaEmamApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXHX3b3P1_BIrFwiZyTLN4H8QN5LFvrg0',
    appId: '1:228865824711:ios:06ecd83f09106042006be2',
    messagingSenderId: '228865824711',
    projectId: 'sukaemam-final-test',
    storageBucket: 'sukaemam-final-test.firebasestorage.app',
    iosClientId: '228865824711-vg0cmm4kad0igibnlmcf0md0p4bqamd9.apps.googleusercontent.com',
    iosBundleId: 'com.example.sukaEmamApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6rRCW8KuHXlWHo8nvtz1oHbuwuWigZoo',
    appId: '1:228865824711:web:00190f0c356ff108006be2',
    messagingSenderId: '228865824711',
    projectId: 'sukaemam-final-test',
    authDomain: 'sukaemam-final-test.firebaseapp.com',
    storageBucket: 'sukaemam-final-test.firebasestorage.app',
    measurementId: 'G-2J64HPKFG0',
  );

}