// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKFlPUWGqqo7FHoWP1SNK9HHhil1ZLRTc',
    appId: '1:348690524507:web:ac97f876342aa10357127e',
    messagingSenderId: '348690524507',
    projectId: 'sukaemam-23',
    authDomain: 'sukaemam-23.firebaseapp.com',
    databaseURL: 'https://sukaemam-23-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sukaemam-23.firebasestorage.app',
    measurementId: 'G-SSVFTJ4QQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzNyXh9JHJJE8Qwj4p4rL3xzg6d_qXXvU',
    appId: '1:348690524507:android:51643cb860ee6c8b57127e',
    messagingSenderId: '348690524507',
    projectId: 'sukaemam-23',
    databaseURL: 'https://sukaemam-23-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sukaemam-23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtriJb-7scYVyxjKxZ4K7k-ZPFxBV_3Gc',
    appId: '1:348690524507:ios:00532d5101029b2057127e',
    messagingSenderId: '348690524507',
    projectId: 'sukaemam-23',
    databaseURL: 'https://sukaemam-23-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sukaemam-23.firebasestorage.app',
    iosClientId: '348690524507-flsaspobdm7pmk8pj71m35h85c2jnm8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.sukaEmamApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtriJb-7scYVyxjKxZ4K7k-ZPFxBV_3Gc',
    appId: '1:348690524507:ios:00532d5101029b2057127e',
    messagingSenderId: '348690524507',
    projectId: 'sukaemam-23',
    databaseURL: 'https://sukaemam-23-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sukaemam-23.firebasestorage.app',
    iosClientId: '348690524507-flsaspobdm7pmk8pj71m35h85c2jnm8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.sukaEmamApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKFlPUWGqqo7FHoWP1SNK9HHhil1ZLRTc',
    appId: '1:348690524507:web:923a0a339695131357127e',
    messagingSenderId: '348690524507',
    projectId: 'sukaemam-23',
    authDomain: 'sukaemam-23.firebaseapp.com',
    databaseURL: 'https://sukaemam-23-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sukaemam-23.firebasestorage.app',
    measurementId: 'G-WZVHBGTGZ5',
  );
}
